### ISSUE TITLE
Error: unable to find release for 2.2.2

### ISSUE THREAD

**Issue by qwezey** [subosito/flutter-action#105]
Not able to use the latest version of flutter (2.2.2) in my workflow

![image](https://user-images.githubusercontent.com/32228262/121763570-2b82c000-cb0b-11eb-8b9a-beda96f05538.png)

![image](https://user-images.githubusercontent.com/32228262/121763595-49e8bb80-cb0b-11eb-9c0b-f3216d8e6c4b.png)

**Comment by qwezey** [comment]
flutter release is hosted under https://storage.googleapis.com/flutter_infra_release/releases whereas `storageUrl` in `src/release.ts` is https://storage.googleapis.com/flutter_infra/releases

seems to be related to #99

**Comment by kuhnroyal** [comment]
It should work with the latest version of the action since it was migrated to the new bucket:
https://storage.googleapis.com/flutter_infra_release/releases/releases_macos.json contains 2.2.2

**Comment by kuhnroyal** [comment]
Nvm, it will not work with 1.5.2, try tag 1.5.1

**Comment by kuhnroyal** [comment]
@subosito reverted the change but the old bucket was not updated for 2.2.2
I asked how this will be handled in the future in https://github.com/flutter/flutter/issues/83746

**Comment by jiangxiaoqiang** [comment]
so, what should I do to fix this problem, I am face the same issue.

**Comment by cuong0993** [comment]
I used v1.5.1 and it works.
      - name: Set up flutter
        uses: subosito/flutter-action@v1.5.1
        with:
          flutter-version: '${{ env.flutter_version }}'

**Comment by jiangxiaoqiang** [comment]
> I used v1.5.1 and it works.
> - name: Set up flutter
> uses: subosito/flutter-action@v1.5.1
> with:
> flutter-version: '${{ env.flutter_version }}'

it works!

**Comment by kuhnroyal** [comment]
@subosito The `flutter_infra_release` is the new bucket going forward.

**Comment by qwezey** [comment]
@subosito old artifacts prior to the migration will however remain in `flutter_infra`

**Comment by kuhnroyal** [comment]
> old artifacts prior to the migration will however remain in `flutter_infra`

That is correct, but they are also available in the new bucket. So it is safe to switch to the new bucket permanently.

**Comment by qwezey** [comment]
> > old artifacts prior to the migration will however remain in `flutter_infra`
> 
> That is correct, but they are also available in the new bucket. So it is safe to switch to the new bucket permanently.

that's perfect!

**Comment by qwezey** [comment]
confirmed, the issue is now resolved
![image](https://user-images.githubusercontent.com/32228262/122653468-9dae6280-d112-11eb-86f0-03b2205a9e20.png)
