### ISSUE TITLE
Provide documentation, why Java is needed.

### ISSUE THREAD

**Issue by nilsreichardt** [subosito/flutter-action#107]
It's very confusing, to set up Java. Therefore, a short comment in the `README.md` why Java is needed, would be very helpful.

**Comment by rk0cc** [comment]
I think is for building Android app, then upload to artifact in action.

**Comment by subosito** [comment]
Yes, @rk0cc answer is correct. I have simplified the README for the `v2` release; I hope it is easier to understand now.
