### ISSUE TITLE
The current Gradle version 4.10.2 is not compatible with the Kotlin Gradle plugin. Please use Gradle 5.3 or newer, or the previous version of the Kotlin plugin.

### ISSUE THREAD

**Issue by jianboy** [subosito/flutter-action#109]
> The current Gradle version 4.10.2 is not compatible with the Kotlin Gradle plugin. Please use Gradle 5.3 or newer, or the previous version of the Kotlin plugin.

**Comment by TheRedSpy15** [comment]
How did you solve this?
