### ISSUE TITLE
A problem occurred evaluating project ':app'.

### ISSUE THREAD

**Issue by jaumard** [subosito/flutter-action#11]
I'm trying your action an end up with this error :/ 

```
A problem occurred evaluating project ':app'.
79
> Flutter SDK not found. Define location with flutter.sdk in the local.properties file.
```
You can see more here: https://github.com/mylisabox/lisa_flutter/commit/7869079fd7645db211856999ef933fc36eb4b87e/checks?check_suite_id=256847402

Am I missing something ?

**Comment by subosito** [comment]
Sorry, just get a chance to check it.

Looks like you already got the solution https://github.com/mylisabox/lisa_flutter/commit/7a6c3402da5bc7ad16591e4f85bc243eed82f43b#diff-90829e76e906f1c73140c7ded7e1b268. 

Going to close this then.
