### ISSUE TITLE
Build failing for APK

### ISSUE THREAD

**Issue by ritvij14** [subosito/flutter-action#112]
https://github.com/ritvij14/cnc_flutter_app/runs/3425406195?check_suite_focus=true

I don't understand why it's failing, it was working fine a couple of days ago and running `flutter build apk` from my terminal makes the apk without any issues.

Please help. TIA

**Comment by jeesang7** [comment]
Did you solve this issue?
If it's an NDK version problem, you can refer to the following.

https://github.com/subosito/flutter-action/issues/116
