### ISSUE TITLE
Build apk is failing: No toolchains found in the NDK toolchains folder for ABI with prefix: arm-linux-androideabi

### ISSUE THREAD

**Issue by Andranjo97** [subosito/flutter-action#116]
When I try to generate an apk in my pipeline, I get the following error:

```
Execution failed for task ':app:stripStgReleaseDebugSymbols'.

> No toolchains found in the NDK toolchains folder for ABI with prefix: arm-linux-androideabi
```

It was working before. I run the pipeline over a commit that I knew passed the pipeline before. However, now it also fails. Did something change in the configurations? Can anyone give me any direction on how to handle this error?

**Comment by jeesang7** [comment]
> When I try to generate an apk in my pipeline, I get the following error:
> 
> ```
> Execution failed for task ':app:stripStgReleaseDebugSymbols'.
> 
> > No toolchains found in the NDK toolchains folder for ABI with prefix: arm-linux-androideabi
> ```
> 
> It was working before. I run the pipeline over a commit that I knew passed the pipeline before. However, now it also fails. Did something change in the configurations? Can anyone give me any direction on how to handle this error?

@Andranjo97 When this problem occurs, it seems that the build locally, not in the pipeline, worked normally without any problems, can you check it?

This problem is suspected of the NDK version problem in the pipeline. @subosito
https://stackoverflow.com/a/61602965

**Comment by Andranjo97** [comment]
@jeesang7 yes it worked locally
