### ISSUE TITLE
Return HTTP 503 when setting one of the channel in macOS platform

### ISSUE THREAD

**Issue by rk0cc** [subosito/flutter-action#118]
It runs normally on Ubuntu and Windows. However, it returns error with HTTP 503 during setup in the macOS with one of the channel.

It look like this (Click the image to my action result):
[![](https://i.imgur.com/Y7bpW5d.png)](https://github.com/rk0cc/will_pub/runs/4079574567?check_suite_focus=true)

**Comment by subosito** [comment]
Closing this, usually, this is a temporary issue.
