### ISSUE TITLE
Quiet output?

### ISSUE THREAD

**Issue by blopker** [subosito/flutter-action#130]
Hey! First off, thanks for making this. Works really well.

One thing I noticed is that the build logs can get pretty long as every time flutter is unzipped (on the Mac runners) every file is listed out.

I was wondering if the `unzip` call could be modified to add the `-q` to quiet the output a bit? My guess is that the action would also run faster as printing output can be expensive. 

So,
```
    unzip -o "$archive_local" -d "$HOME"
```
to
```
    unzip -q -o "$archive_local" -d "$HOME"
```

Thanks!

**Comment by blopker** [comment]
Nice! Thanks.

**Comment by subosito** [comment]
You're welcome @blopker, thanks for the suggestion 👍

**Comment by blopker** [comment]
Great, I wanted to follow up and say this action went from 53 to 39 seconds on my macos builds.
