### ISSUE TITLE
bug: can't run flutter on macOS

### ISSUE THREAD

**Issue by SiongSng** [subosito/flutter-action#146]
The system architecture of GitHub Action is `x86` not `arm64`, so should download the x86 archive.
Error: `Bad CPU type in executable`
PR: https://github.com/subosito/flutter-action/pull/147
![image](https://user-images.githubusercontent.com/48402225/163669506-4903b488-1920-4f8b-bc1a-b5bd73b66220.png)
![image](https://user-images.githubusercontent.com/48402225/163669417-49e2778e-9892-4121-a2a2-6ba581876f8d.png)

**Comment by MATTYGILO** [comment]
How do I get the fix?

**Comment by subosito** [comment]
@MATTYGILO For now, you can use `subosito/flutter-action@main`. I will be releasing a new version soon.

**Comment by zhujiageng** [comment]
@subosito after use `subosito/flutter-action@main`, i got error:
`Because every version of flutter from sdk depends on sky_engine from sdk which is forbidden, flutter from sdk is forbidden.
So, because arcsite_flutter depends on flutter from sdk, version solving failed.`
