### ISSUE TITLE
Allow us to set flutter tools directory

### ISSUE THREAD

**Issue by ekasetiawans** [subosito/flutter-action#160]
Currently, the flutter tools will be saved at `${RUNNER_TEMP}/flutter`. 
I have an issue when I run the action on **self-hosted runner** and I have multiple projects with different flutter channel (for example some projects using master channel and also others using stable). It's can be solved with executing extra step to change the flutter channel, but it will take more runner execution time to download the sdk.

If we able to set the tools directory for example ${RUNNER_TEMP}/flutter_master` for master channel or ${RUNNER_TEMP}/flutter_stable` for stable channel, then it will make our runner execution faster because the runner will not re-downloading the sdk if it already downloaded.

**Comment by subosito** [comment]
@ekasetiawans `flutter-action@v2` are capable of customizing the `cache-path` for your use case. Please refer to the README for more information about it.
