### ISSUE TITLE
Arm64 machine not supported.

### ISSUE THREAD

**Issue by wangmir** [subosito/flutter-action#161]
Since flutter 3.0.0 supports apple silicon native support,
I tried to change the architecture of action to arm64 for macos build.

but it failed with this message,
```
/Users/runner/hostedtoolcache/flutter/bin/internal/shared.sh: line 225: /Users/runner/hostedtoolcache/flutter/bin/cache/dart-sdk/bin/dart: Bad CPU type in executable
```

**Comment by wangmir** [comment]
When I tried to change cache key and path, it still failed..

```
Run flutter pub get
  flutter pub get
  shell: /bin/bash -e {0}
  env:
    FLUTTER_ROOT: /Users/runner/hostedtoolcache/flutter_arm
    PUB_CACHE: /Users/runner/hostedtoolcache/flutter_arm/.pub-cache
/Users/runner/hostedtoolcache/flutter_arm/bin/internal/shared.sh: line [2](https://github.com/ming-app/ming/runs/6439098507?check_suite_focus=true#step:4:2)2[5](https://github.com/ming-app/ming/runs/6439098507?check_suite_focus=true#step:4:5): /Users/runner/hostedtoolcache/flutter_arm/bin/cache/dart-sdk/bin/dart: Bad CPU type in executable
Error: Process completed with exit code 1.
```

**Comment by yurikoles** [comment]
Is this a self-hosted runner with arm64 CPU?

**Comment by Jesperpaulsen** [comment]
I'm experiencing the same problem on Github Actions now

**Comment by kuhnroyal** [comment]
You have to use the action `2.4.0` and if you have enabled the cache, you need to make sure that the key contains the architecture.
On a self-hosted runner disable caching, clear the `/Users/runner/hostedtoolcache/flutter` folder and try again with `2.4.0` - it works.

**Comment by subosito** [comment]
Thanks @kuhnroyal!
