### ISSUE TITLE
Sometimes getting `Assertion failed: (timeout != -1), function uv__io_poll, file ../deps/uv/src/unix/kqueue.c, line 256.`

### ISSUE THREAD

**Issue by nilsreichardt** [subosito/flutter-action#189]
Sometimes fails our CI because of 
```
Assertion failed: (timeout != -1), function uv__io_poll, file ../deps/uv/src/unix/kqueue.c, line 256.`
```

<img width="1082" alt="image" src="https://user-images.githubusercontent.com/24459435/192724947-7928be8f-7212-4354-a132-a7785b5c5888.png">

Our app is open source. You find the logs here:
https://github.com/SharezoneApp/sharezone-app/actions/runs/3138556983/jobs/5098015831

This is our flow that is sometimes failing:
https://github.com/SharezoneApp/sharezone-app/blob/ea6d6ab75b72b3224d15cf5d37f4cffafc89281a/.github/workflows/main.yml#L127

Any ideas?

**Comment by subosito** [comment]
@nilsreichardt Please retry using `subosito/flutter-action@v2` instead of `v1`.

**Comment by nilsreichardt** [comment]
Thanks, I will try 👍

**Comment by nilsreichardt** [comment]
I'm going to close this ticket for now. If this issue happens again, I'm going to reopen this ticket.
