### ISSUE TITLE
set-output is deprecated

### ISSUE THREAD

**Issue by rpekarek-tc** [subosito/flutter-action#192]
Warning message: The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

**Comment by subosito** [comment]
@rpekarek-tc Just published `v2.8.0` and also updated `v2` to fix this. Thanks for reporting.
