### ISSUE TITLE
Add dart to the $PATH

### ISSUE THREAD

**Issue by pavanpodila** [subosito/flutter-action#21]
It would be good to put the Dart binaries on $PATH

**Comment by subosito** [comment]
Hi @pavanpodila, thanks for the suggestion, we can add this later when enough demand for this. For now, you can do:

```yaml
- run: echo ::add-path::${FLUTTER_HOME}/bin/cache/dart-sdk/bin
- run: dart --version
```

**Comment by shouichi** [comment]
We need this feature too.

Background: We run a mock server written in dart for `flutter drive`.
