### ISSUE TITLE
`dev` channel seem to be outdated

### ISSUE THREAD

**Issue by asashour** [subosito/flutter-action#218]
As `master` was dropped, moving to `dev` isn't returning Dart SDK 3.

Instead:

```
The current Dart SDK version is 2.17.0-266.1.beta.

Because <project> requires SDK version >=2.19.0 <4.0.0, version solving failed.
```

Beta version works fine.

**Comment by subosito** [comment]
`dev` channel has been deprecated, I keep it for backward compatibility, to download the older version, only. Yes, please use `beta`.
