### ISSUE TITLE
Action fails on self-hosted windows runner

### ISSUE THREAD

**Issue by bekaIva** [subosito/flutter-action#239]
![image](https://github.com/subosito/flutter-action/assets/7364901/be19b218-443b-4a43-bd90-6e7b562c9532)
It appears that the slashes are missing from the path, which is causing the issue and the file actually is created at the path `C:\Users\bivan\Documents\GithubRunner\actions-runner\_work\_temp\a579c70d-dabb-4a34-8ce1-7c0035cc07fd.sh`

**Comment by bekaIva** [comment]
I set my environment variables to use git bash instead of wsl and now it works.
Problem was in echo "$RUNNER_OS"

**Comment by prinkeeras** [comment]
How did you fix this?
