### ISSUE TITLE
Unexpected HTTP response: 404 when ommit channel and specify flutter-version

### ISSUE THREAD

**Issue by bierbaumtim** [subosito/flutter-action#24]
I've get this error when I specify flutter-version and ommit channel.
```
##[error]Unexpected HTTP response: 404
``` 
I get the error on v1 and v1.1.1.

If I understand the description correctly, channel isn't since October 2019 supported and you need to use flutter-version. 

If I wrong, how can I use the master version of flutter ?

**Comment by subosito** [comment]
We only support channels with installation bundles from https://flutter.dev/docs/development/tools/sdk/releases, which are `stable`, `beta` and `dev`.

We don't use `v` prefix for version.

Something like this should be working fine:

```yaml
- uses: subosito/flutter-action@v1
  with:
    flutter-version: '1'
```
