### ISSUE TITLE
How do I pull 3.10.7?

### ISSUE THREAD

**Issue by larry-cariq** [subosito/flutter-action#242]
I am not able to pull the Flutter version 3.10.7 because it is not setup in a channel. I've tried using the channels stable and any and it still does not work. Is there a way to pull version 3.10.7?

Reference: https://github.com/flutter/flutter/wiki/Upgrading-from-3.10.6-to-3.10.7

Here are my results:
```
Run subosito/flutter-action@v2
Run $GITHUB_ACTION_PATH/setup.sh -p -c '/Users/runner/hostedtoolcache/flutter/:channel:-:version:-:arch:' -k 'flutter-:os:-:channel:-:version:-:arch:-:hash:' -n '3.10.7' -a 'X64' any
Unable to determine Flutter version for channel: any version: 3.10.7 architecture: x64
Error: Process completed with exit code 1.
```

**Comment by rpekarek-tc** [comment]
Any update on this?

**Comment by JhonyPerez** [comment]
To solve this we are using this action to set the flutter version to 3.10.6, and then manually changing to the flutter directory and checking out 3.10.7 from there.

```
- name: 'Set Flutter 3.10.6'
   uses: subosito/flutter-action@v2
   with:
       flutter-version: 3.10.6
```

```
- name: 'Checkout Flutter 3.10.7'
   shell: bash
   run: |
     cd $FLUTTER_ROOT;
     git fetch --tags;
     git checkout 3.10.7;
     flutter --version;
```

**Comment by larry-cariq** [comment]
@JhonyPerez Those shell commands worked well. Thanks.
