### ISSUE TITLE
Failed to download Actions

### ISSUE THREAD

**Issue by nishp77** [subosito/flutter-action#26]
Hi i did setup the .yml file `  #The name of your workflow.
  name: Flutter Testing

  #Trigger the workflow on push or pull request
  on: [push,pull_request]

  #A workflow run is made up of one or more jobs. Jobs run in parallel by default.
  jobs:

    test:
      #The type of machine to run the job on. [windows,macos, ubuntu , self-hosted]
      runs-on: ubuntu-latest
      #sequence of tasks called
      steps:
        # The branch or tag ref that triggered the workflow will be checked out.
        # https://github.com/actions/checkout
        - uses: actions/checkout@v1
        - uses: actions/setup-java@v1
          with:
            java-version: '12'
        # Setup a flutter environment.
        # https://github.com/marketplace/actions/flutter-action
        - uses: subosito/flutter-action@v1.2.0;
          with:
            channel: 'stable'
        - run: flutter pub get
        # run static analys code
        - run: flutter  analyze
        # run  flutter widgets tests  and unit tests
        - run: flutter test --coverage
`

The CI output: -

Current runner version: '2.165.2'
Prepare workflow directory
Prepare all required actions
Download action repository 'actions/checkout@v1'
Download action repository 'actions/setup-java@v1'
Download action repository 'subosito/flutter-action@v1.2.0;'
##[warning]Failed to download action 'https://api.github.com/repos/subosito/flutter-action/tarball/v1.2.0;'. Error Response status code does not indicate success: 404 (Not Found).
##[warning]Back off 27.431 seconds before retry.
##[warning]Failed to download action 'https://api.github.com/repos/subosito/flutter-action/tarball/v1.2.0;'. Error Response status code does not indicate success: 404 (Not Found).
##[warning]Back off 26.915 seconds before retry.
##[error]Response status code does not indicate success: 404 (Not Found)

**Comment by subosito** [comment]
There is a typo, please update to:

```diff
-    - uses: subosito/flutter-action@v1.2.0;
+    - uses: subosito/flutter-action@v1.2.0
```
