### ISSUE TITLE
Update tags please?

### ISSUE THREAD

**Issue by valerauko** [subosito/flutter-action#271]
In general actions are tagged so that
action@v1 is the latest 1.x.x
action@v1.1 is the latest 1.1.x
and action@v1.1.1 is exaclty 1.1.1

Could you please update tags to work like that? I was using `@v2` assuming it gets updated

**Comment by subosito** [comment]
We use that, except for `action@v1.1 is the latest 1.1.x` part. I don't think this is needed since the version is so simple now.
