### ISSUE TITLE
Cache action has a new version available

### ISSUE THREAD

**Issue by sebastianbuechler** [subosito/flutter-action#273]
I get a deprecation warning when using the current version of this action:
Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: actions/cache@v3. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.

Is it possible to update the action/cache dependency to v4?

Edit: Saw that it's already done in https://github.com/subosito/flutter-action/pull/264/commits/06270ec3e62e5a35f4cad7f8d61b14e7b0a6cf90 but still needs a new version to be released with the upgrade.

**Comment by P-Jay357** [comment]
Yeah, like you said they've done a few commits since the last release to do with caching. I'm looking forward to the next release so that we can cache the pub dependencies + get rid of that pesky Node.js 16 warning!

**Comment by subosito** [comment]
Sure, I just released version `v2.13.0` and updated `v2` with this update.

**Comment by sebastianbuechler** [comment]
@subosito awesome, thanks!

**Comment by P-Jay357** [comment]
Brilliant! Thanks :)
