### ISSUE TITLE
Right path for ~/.pub-cache

### ISSUE THREAD

**Issue by SBNTT** [subosito/flutter-action#28]
Hi

I need to write some json into this file: `~/.pub-cache/credentials.json` for deploying a package to dart.dev

I've this step in my workflow:
```yaml
- run: | 
    mkdir -p ~/.pub-cache 
    echo '${{ secrets.PUB_DEV_CREDENTIALS }}' > ~/.pub-cache/credentials.json
```

Deployment is still asking me for authorization, so I think `~/.pub-cache` is not the right path but I don't know how to find the right one.

thanks

**Comment by xvrh** [comment]
I think `$FLUTTER_HOME/.pub-cache/credentials.json` works

```
        run: |
          mkdir -p $FLUTTER_HOME/.pub-cache
          echo '${{ secrets.PUB_DEV_CREDENTIALS }}' >  $FLUTTER_HOME/.pub-cache/credentials.json
```
