### ISSUE TITLE
Action taking long time to setup

### ISSUE THREAD

**Issue by jl-gogovapps** [subosito/flutter-action#29]
Hello, thanks for the great work here, I've found this action extremely useful!
I was wondering how long it is expected to take to set up the flutter-action.  For both 1.1 and 1.2, I've recently noticed the time to setup exceeding 15 minutes.  

Note -  I'm using this against Githubs OSX VMs, not a dedicated host. 

Thanks in advance!

<img width="1562" alt="Screen Shot 2020-04-02 at 8 45 53 AM" src="https://user-images.githubusercontent.com/44532602/78250771-60829400-74be-11ea-950e-135d4eb4d38a.png">

**Comment by campovski** [comment]
Same here, taking 10+ minutes on macOS GitHub Actions runner.

**Comment by sdstolworthy** [comment]
Yeah, +1 here. It takes anywhere from 5 to 10 minutes to set up on the mac runner.

**Comment by subosito** [comment]
I've added a test to check this, as you can see on https://github.com/subosito/flutter-action-example/runs/1223936721?check_suite_focus=true.

I am going to close this issue. Feel free to reopen if the issue persists, and I will dig more about that :)
