### ISSUE TITLE
Flutter project not in root of repo, fails.

### ISSUE THREAD

**Issue by MisterJimson** [subosito/flutter-action#3]
If you have a Flutter project in a folder in your repo, this action will fail.

Maybe support a param to specify the folder to the Flutter project and just default to root?
```
Run flutter pub get
Error: No pubspec.yaml file found.
This command should be run from the root of your Flutter project.
Do not run this command from the root of your git clone of Flutter.
##[error]Process completed with exit code 1.
```

**Comment by subosito** [comment]
I think you can use `cd` on your run section, like: `cd path/to/project && flutter pub get` or set `working-directory` on [steps section](https://help.github.com/en/articles/workflow-syntax-for-github-actions#jobsjob_idstepsworking-directory)
