### ISSUE TITLE
Support for FVM

### ISSUE THREAD

**Issue by martyfuhry** [subosito/flutter-action#307]
Our project uses [fvm](https://fvm.app/) for version management. I wonder if you have any guidance for setting up `flutter-action` to use the version of Flutter configured by the `.fvmrc` file. An example file is:

```json
{
  "flutter": "3.19.1",
  "flavors": {
    "development": "beta",
    "production": "3.19.1"
  },
  "updateVscodeSettings": true,
  "updateGitIgnore": true,
  "runPubGetOnSdkChanges": true
}
```

Can I simply read the `flutter` key from this file into the `flutter-version:` parameter? Maybe you have built-in support?

Thank you!

**Comment by gyan786fyers** [comment]
What is the use of this action if we can't use fvm commands ? @kuhnroyal @subosito
