### ISSUE TITLE
Failed to compile: VisualDensity.adaptivePlatformDensity

### ISSUE THREAD

**Issue by alexhenriquepv** [subosito/flutter-action#31]
### The action is falling with this configuration:
![image](https://user-images.githubusercontent.com/12400276/79033232-95f04700-7b7a-11ea-9eba-464743dc6e2d.png)

### Below the error log.
![image](https://user-images.githubusercontent.com/12400276/79033208-59bce680-7b7a-11ea-87c7-f5e0d7dd38f8.png)

### The flutter repository call the version with name '**v1.15.17**' but fail too.

**Comment by alexhenriquepv** [comment]
### I found the bug. Working on this.

![image](https://user-images.githubusercontent.com/12400276/79034408-aa850d00-7b83-11ea-8a91-5efcd24197ec.png)

See that the correct would be `flutter_linux_1.17.0-dev.3.1` instead of `flutter_linux_v1.17.0-dev.3.1`

**Comment by subosito** [comment]
Hi @alexhenriquepv, please try [v1.3.0](https://github.com/subosito/flutter-action/releases/tag/v1.3.0) or v1, I've updated that to support the new release format.

**Comment by alexhenriquepv** [comment]
### Nice. It works. Thank's brow!

**Comment by alexhenriquepv** [comment]
You are from Indonesia, right? Is everything okay out there?

**Comment by subosito** [comment]
Awesome, glad to hear that @alexhenriquepv 😄. Everything is ok here, but there is a significant slowdown in some sectors due to covid-19. What about you in Brazil?

**Comment by alexhenriquepv** [comment]
Well. Locked in quarantine, installing the new version of Deepin 😄. See you!
