### ISSUE TITLE
Custom java version

### ISSUE THREAD

**Issue by mbfakourii** [subosito/flutter-action#316]
How to select specific java version like 17 to build apk?

**Comment by mbfakourii** [comment]
The problem was solved with the code below

```dart
- uses: actions/setup-java@v4
  with:
    distribution: 'oracle'
    java-version: '17'
- name: Setup flutter
  uses: subosito/flutter-action@v2
  with:
    channel: 'stable'
    cache: true
```

But maybe it would be better to add an option to flutter-action to select the java version

**Comment by yurikoles** [comment]
> But maybe it would be better to add an option to flutter-action to select the java version

To understand the nonsense of your proposal consider requesting to set up a specific version of `flutter` in the [Setup Java Action](/actions/setup-java) repository.

**Comment by mbfakourii** [comment]
> > But maybe it would be better to add an option to flutter-action to select the java version
> 
> Why don't you request ability to set up a specific version of the `flutter` in the [Setup Java Action](/actions/setup-java) repository?

Because Flutter uses java to build its apk!

**Comment by yurikoles** [comment]
Flutter doesn't use any Java to build for iOS, macOS, Linux and Windows. 

My main point is to set up a specific language or framework with a particular setup action in order to reinvent a wheel and to follow the DRY principle.
