### ISSUE TITLE
Why to use bash as shell on Windows?

### ISSUE THREAD

**Issue by WilliamKarolDiCioccio** [subosito/flutter-action#324]
The action is said to be Windows compatible and no additional configuration steps are mentioned in the README.md, then why is the action using [bash](https://github.com/subosito/flutter-action/blob/44ac965b96f18d999802d4b807e3256d5a3f9fa1/action.yaml#L78)? Can't setup scripts be translated to .bat or .ps1 for Windows? This would make our lives much easier. Is there something I'm missing, or this can objectively be improved?

**Comment by yurikoles** [comment]
In fact, `bash` is also Windows compatible.

**Comment by WilliamKarolDiCioccio** [comment]
I was wrong saying this but I got pretty confused because I was testing the workflow locally on my machine using Act so my dev env configuration influenced the results. I've now fixed the issue. Than you for you answer. Let's close this silly issue 😊
