### ISSUE TITLE
Flock - How to specify which Flutter repository to use

### ISSUE THREAD

**Issue by xni06** [subosito/flutter-action#331]
With the arrival of [Flock](https://getflocked.dev), we would like to specify which Flutter repository to clone. 

Currently, https://github.com/flutter/flutter.git is used but we would like to have the option to specify the URL, which in this case would be https://github.com/Flutter-Foundation/flutter.git

We can see that `setup.sh` has the following [line](https://github.com/subosito/flutter-action/blob/bcec24ecf7bef7763f50dcf9a91533853b686ae2/setup.sh#L216) that may be of relevance:

```sh
git clone -b "$CHANNEL" https://github.com/flutter/flutter.git "$CACHE_PATH"
```

Is this at all possible? Thanks.

**Comment by bartekpacia** [comment]
related #308
