### ISSUE TITLE
Unable to fetch flutter release on macos

### ISSUE THREAD

**Issue by nebis-software** [subosito/flutter-action#339]
Hi!
   since today I get the following error on mac:

```

 ./install_flutter.sh 3.24.5

Fetching Flutter SDK release manifest...

::debug::FLUTTER_RELEASE_VERSION=3.24.5

::debug::FLUTTER_RELEASE_SHA256=null

::debug::FLUTTER_RELEASE_ARCHIVE=null

Installing Flutter SDK version: 3.24.5 (stable) on "macos_x86_64" ...

Downloading https://storage.googleapis.com/flutter_infra_release/releases/null

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current

                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0

100   197  100   197    0     0   2715      0 --:--:-- --:--:-- --:--:--  2736

Verifying checksum: shasum: standard input: no properly formatted SHA checksum lines found

::error::Checksum verification failed! Please check passed arguments.

```

uname says:

```
 uname -sm

Darwin x86_64


```

I am manually using the "install_flutter.sh" from within Xcode cloud. It has been working nicely in the past 6 months.
Maybe something changed in the flutter chain?  Checking the link

`https://storage.googleapis.com/flutter_infra_release/releases/releases_macos.json
`
it seems that x86_64 is not a  valid "dart_sdk_arch"  , I see only x64

Thanks!

**Comment by bartekpacia** [comment]
Hey,

What is `install_flutter.sh`?

>  it seems that x86_64 is not a valid "dart_sdk_arch" , I see only x64

Yeah, Dart uses `x64` for x86-64/amd64, and `arm64` for arm64.
