### ISSUE TITLE
beta channel build breaks with updated dependency

### ISSUE THREAD

**Issue by rich-j** [subosito/flutter-action#40]
We use the Flutter `beta` channel both locally and in our GitHub actions. We just updated our project dependency on [provider](https://pub.dev/packages/provider) to `4.1.1`. Our app successfully builds locally but fails on GitHub with

```
Run flutter build web --target=lib/main_web.dart
  flutter build web --target=lib/main_web.dart
  shell: /bin/bash -e {0}
  env:
    FLUTTER_HOME: /opt/hostedtoolcache/flutter/1.17.0-3.4.pre-beta/x64
Downloading Web SDK...                                              0.8s
Running "flutter pub get" in x_app...                     
The current Flutter SDK version is 1.17.0-3.4.pre.

Because provider 4.1.1 requires Flutter SDK version >=1.17.0 and no versions of provider match >4.1.1 <5.0.0, provider ^4.1.1 is forbidden.

So, because x_app depends on provider ^4.1.1, version solving failed.
```

Locally we show the `beta` channel to be

```
Flutter is already up to date on channel beta
Flutter 1.17.0 • channel beta • https://github.com/flutter/flutter.git
Framework • revision e6b34c2b5c (9 days ago) • 2020-05-02 11:39:18 -0700
Engine • revision 540786dd51
Tools • Dart 2.8.1
```

This seems related to the fix https://github.com/subosito/flutter-action/issues/39 .

**Comment by subosito** [comment]
Hi @rich-j, thanks for the report. This action already does the correct thing, it's downloading the latest beta according to information in https://flutter.dev/docs/development/tools/sdk/releases. As you can see the latest `beta` is `1.17.0-3.4.pre`. The `1.17.0` only available to `stable` channel.

I think this related to [release process](https://medium.com/flutter/flutter-spring-2020-update-f723d898d7af) update. In the meantime, you need to handle the upgrade yourself, until we have confirmation from the flutter team about this.

```
      - uses: subosito/flutter-action@v1
        with:
          channel: 'beta'
      - run: flutter channel beta
      - run: flutter upgrade
```

Please let me know if you have any other recommendation.

**Comment by rich-j** [comment]
Thanks @subosito, adding the explicit `- run: flutter channel beta` fixes our build. The `- run: flutter upgrade` didn't seem to matter (`flutter-action` already downloaded the most recent release) but it's probably a good check.

We had tried to change `flutter-action` to use the `stable` channel but our build failed with `"build web" is not currently supported.` Even though we enabled Flutter web support it seems there's an explicit check for which channel is current. We didn't think about your fix to explicitly enable the beta channel.

**Comment by rich-j** [comment]
@subosito, an additional note - We didn't think to explicitly set the Flutter channel to beta since we incorrectly assumed it was being done by `flutter-action` with `channel: 'beta'`.

**Comment by subosito** [comment]
Hi @rich-j the channel is already correct, it has the same value as the channel option. I was ensuring (and this was optional), it's being set to a specific channel before running the upgrade. So basically, you only need to run `flutter upgrade` to get the `1.17.0` on beta channel.

Here's the full overview:

```
$ tar xf flutter_linux_1.17.0-3.4.pre-beta.tar.xz
$ cd flutter
$ export PATH=$PWD/bin:$PATH

$ flutter --version
Flutter 1.17.0-3.4.pre • channel beta • https://github.com/flutter/flutter.git
Framework • revision e6b34c2b5c (10 days ago) • 2020-05-02 11:39:18 -0700
Engine • revision 540786dd51
Tools • Dart 2.8.1

$ flutter channel
Flutter channels:
  master
  dev
* beta
  stable
  
$ git log -1
commit e6b34c2b5c96bb95325269a29a84e83ed8909b5f (HEAD -> beta, tag: 1.17.0-3.4.pre, origin/flutter-1.17-candidate.3, origin/beta)
Author: Patrick Sosinski <sosinski@google.com>
Date:   Sat May 2 11:39:18 2020 -0700

    Update engine version. (#56178)
    
$ flutter upgrade
Flutter is already up to date on channel beta
Flutter 1.17.0-3.4.pre • channel beta • https://github.com/flutter/flutter.git
Framework • revision e6b34c2b5c (10 days ago) • 2020-05-02 11:39:18 -0700
Engine • revision 540786dd51
Tools • Dart 2.8.1

$ git log -1
commit e6b34c2b5c96bb95325269a29a84e83ed8909b5f (HEAD -> beta, tag: 1.17.0-3.4.pre, tag: 1.17.0, origin/stable, origin/beta)
Author: Patrick Sosinski <sosinski@google.com>
Date:   Sat May 2 11:39:18 2020 -0700

    Update engine version. (#56178)
    
$ flutter --version
Flutter 1.17.0 • channel beta • https://github.com/flutter/flutter.git
Framework • revision e6b34c2b5c (10 days ago) • 2020-05-02 11:39:18 -0700
Engine • revision 540786dd51
Tools • Dart 2.8.1
```
