### ISSUE TITLE
Release for iOS

### ISSUE THREAD

**Issue by mfgabriel92** [subosito/flutter-action#42]
How do I generate a release for iOS?

**Comment by kitek** [comment]
Building an iOS app with flutter might be a little bit tricky.
I would recommend this [tutorial](https://flutter.dev/docs/deployment/ios) with a tool called [Fastlane](https://fastlane.tools/).

**Comment by RicardoRB** [comment]
Check #30

**Comment by subosito** [comment]
Closed by #30
