### ISSUE TITLE
flutter drive?

### ISSUE THREAD

**Issue by ghenry** [subosito/flutter-action#57]
Hi all,

I know you need the simulator, but thought I'd ask if I could run:

` - run: flutter drive --target=test_driver/app.dart`

Thanks.

**Comment by themightychris** [comment]
yes

**Comment by ghenry** [comment]
Thanks. Should have just tried it.

**Comment by ghenry** [comment]
Thanks. I can't see how to start a device though?

```
Run flutter drive --target=test_driver/app.dart
  flutter drive --target=test_driver/app.dart
  shell: /bin/bash -e {0}
  env:
    SSH_AUTH_SOCK: /var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T//ssh-EN8LpKh3bsXB/agent.734
    SSH_AGENT_PID: 735
    FLUTTER_HOME: /Users/runner/hostedtoolcache/flutter/1.22.0-stable/x64
No devices found.
Error: Process completed with exit code 1.
```

**Comment by clint-gossett-tilliden** [comment]
> Thanks. I can't see how to start a device though?
> 
> ```
> Run flutter drive --target=test_driver/app.dart
>   flutter drive --target=test_driver/app.dart
>   shell: /bin/bash -e {0}
>   env:
>     SSH_AUTH_SOCK: /var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T//ssh-EN8LpKh3bsXB/agent.734
>     SSH_AGENT_PID: 735
>     FLUTTER_HOME: /Users/runner/hostedtoolcache/flutter/1.22.0-stable/x64
> No devices found.
> Error: Process completed with exit code 1.
> ```

Did you find an answer to your question?  I have a device enabled once I run flutter --enable-<platform>-desktop.  I'm following this tutorial.  https://medium.com/flutter-community/run-flutter-driver-tests-on-github-actions-13c639c7e4ab

**Comment by clint-gossett-tilliden** [comment]
All, I had a lot of issues getting flutter driver to work.  Here's to the solution I hacked together. https://stackoverflow.com/questions/64759960/error-while-running-flutter-driver-on-github-actions-macos

I'm not sure if this is an issue with Flutter Driver or with the flutter-action.
