### ISSUE TITLE
Change the working directory

### ISSUE THREAD

**Issue by guyluz11** [subosito/flutter-action#59]
[The page of the Action](https://github.com/marketplace/actions/flutter-action) didn't showed any example changing the working directory.
Is it supported? and if it does can we add example or explanation how to use it?.

**Comment by digodk** [comment]
@guyluz11 have you found out how to do it?

**Comment by guyluz11** [comment]
Can't remember

I think you can do
`run: cd x/y/z`
`run: flutter build`

Or use `melos`
