### ISSUE TITLE
folder name

### ISSUE THREAD

**Issue by Kleak** [subosito/flutter-action#6]
Could we rename this part `1.9.1-hotfix.2-stable` of this folder `/opt/hostedtoolcache/flutter/1.9.1-hotfix.2-stable` to just `stable` in the case we use the action like that 
```
    - uses: subosito/flutter-action@v1
      with:
        channel: 'stable'
```
What i would like is to be able to add the credentials.json to the .pub-cache folder to automatically upload my package to pub without modifying the cd pipeline.

**Comment by subosito** [comment]
@Kleak I don't think it's a good idea, there will be an issue when the stable channel gets updated, and the cache will be stuck to the locally available version.
