### ISSUE TITLE
Build iOS App

### ISSUE THREAD

**Issue by mirkancal** [subosito/flutter-action#7]
Is there a way to build an iOS app with this action?

**Comment by joeblew99** [comment]
me too !!

**Comment by stefandevo** [comment]
Not sure (have not yet tried it), but you can add
`- run: flutter build ios`

ref https://flutter.dev/docs/deployment/cd

**Comment by tianhaoz95** [comment]
use `flutter build ios  --release --no-codesign` otherwise, it won't complete in 6 hours. It will get stuck. I remember it was a bug in Flutter, forgot the issue number tho.

**Comment by RicardoRB** [comment]
Check this #30

**Comment by subosito** [comment]
Closed by #30
