### ISSUE TITLE
Installation location for the Flutter SDK

### ISSUE THREAD

**Issue by yulingtianxia** [subosito/flutter-action#75]
Where is flutter unzipped? I want to run flutter command by these dart code:

``` dart
Process.runSync('flutter', ['doctor'])
```

But failed：

``` bash
ProcessException: The system cannot find the file specified.
Command: flutter doctor
```

**Comment by subosito** [comment]
@yulingtianxia, I am not sure what is your code looks like, but I just tested it, and it works fine:

https://github.com/subosito/flutter-action-example/tree/path
https://github.com/subosito/flutter-action-example/runs/2480537474?check_suite_focus=true

Feel free to reopen if the issue persists on your side.
