### ISSUE TITLE
Setting up flutter on macos takes too long

### ISSUE THREAD

**Issue by daniilshumkoidt** [subosito/flutter-action#80]
Today I have noticed that using this action takes almost 10 times longer then it use to take yesterday. I am trying to set up Flutter using the latest stable build. It used to take under 1 min to run this action and now it takes around 9 minutes. 
Has anyone noticed this and does anyone have any information about why this could be happening?

**Comment by yurikoles** [comment]
Seems to be upstream issue: https://github.com/actions/virtual-environments/issues/430

**Comment by daniilshumkoidt** [comment]
Looks like it is back to normal
