### ISSUE TITLE
Will the Dart support for GitHub Actions will bring any benefits?

### ISSUE THREAD

**Issue by daniil-shumko** [subosito/flutter-action#82]
Just read [this blog](https://medium.com/dartlang/announcing-dart-support-for-github-actions-3d892642104) and it looks like the Dart team added an action that can set up Dart on the VMs.

Will this lead to any improvements to this action?

**Comment by blopker** [comment]
It looks like at the bottom of that post they recommend using this action for Flutter apps still.

**Comment by subosito** [comment]
Well, it inspired me to rewrite this action using shell script and just released it as `subosito/flutter-action@v2` 😄

**Comment by daniil-shumko** [comment]
Thanks for your work @subosito! 🎉
