### ISSUE TITLE
pub-cache path different for flutter and dart

### ISSUE THREAD

**Issue by kuhnroyal** [subosito/flutter-action#89]
The action makes the `flutter` and `dart` executables available.
`flutter` uses `$FLUTTER_ROOT/.pub-cache`
`dart` uses `$HOME/.pub-cache`

It would be great if both use the same path and also if `PUB_CACHE` variable was exported to env.
This should only be set if it does not already exist in the env.

**Comment by subosito** [comment]
@kuhnroyal I think this is a good idea to have the same path for `dart` and `flutter` cache. Do you think there is any potential issue with this? In your PR, we will use `$FLUTTER_ROOT/.pub-cache`, isn't it?

**Comment by kuhnroyal** [comment]
> In your PR, we will use `$FLUTTER_ROOT/.pub-cache`, isn't it?

Yes, exactly

**Comment by subosito** [comment]
Ok, got it. Thanks @kuhnroyal
