### ISSUE TITLE
Server-side build failure (GCS: "Access Denied")

### ISSUE THREAD

**Issue by ndahlquist** [subosito/flutter-action#99]
It appears that the plugin has stopped working sometime within the last 2 days, likely due to a server-side permissions change on how the Flutter releases are being served.

```
Run subosito/flutter-action@v1.5.0
  with:
    flutter-version: 2.2.1
    channel: stable
Error: <?xml version='1.0' encoding='UTF-8'?><Error><Code>AccessDenied</Code><Message>Access denied.</Message><Details>Anonymous caller does not have storage.objects.get access to the Google Cloud Storage object.</Details></Error>
```

Please let me know if any further information is helpful for debugging.

**Comment by kittytastic** [comment]
I'm having the same issue.

**Comment by thewolfaxe** [comment]
Yeah I got the same thing here

**Comment by subosito** [comment]
Yep, I just confirmed this issue in https://github.com/subosito/flutter-action-example/runs/2723523792?check_suite_focus=true. Any idea on an updated URL that provides release data?

**Comment by qwezey** [comment]
yesterday my workflows were working fine. I noticed the issue today

**Comment by tuanvugoodmoney** [comment]
@subosito see #100

**Comment by daniel7byte** [comment]
I'm having the same issue.

**Comment by subosito** [comment]
Just merged the #100 and released `v1.5.1` as well as updated `v1`. It should be ok now.

**Comment by ndahlquist** [comment]
Confirmed fixed for me! Thank you! 🥇

**Comment by kuhnroyal** [comment]
It looks like this change should be reverted. Everything is back to normal.
